# Generated by Django 4.0 on 2022-02-25 09:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field='300', upload_to='about/images/', width_field='300')),
                ('paragraph', models.TextField(max_length=450)),
                ('experience', models.TextField(max_length=450)),
                ('e_year', models.DateTimeField()),
                ('skill_sub', models.CharField(max_length=200)),
                ('s_percents', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200, validators=[django.core.validators.EmailValidator])),
                ('phone', models.CharField(default='+880-', max_length=200)),
                ('messages', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomePageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(max_length=200)),
                ('text2', models.CharField(max_length=200)),
                ('text3', models.CharField(max_length=200)),
                ('paragraph', models.CharField(max_length=450)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(height_field='250', upload_to='portfolio/images/', width_field='250')),
                ('images', models.ImageField(height_field='350', upload_to='portfolio/images/', width_field='400')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
