# Generated by Django 4.0 on 2022-02-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapi', '0004_alter_aboutmemodel_image_alter_portfoliomodel_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliomodel',
            name='images',
            field=models.ImageField(height_field=250, upload_to='portfolio/images/', width_field=250),
        ),
    ]
