# Generated by Django 4.0 on 2022-02-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapi', '0005_alter_portfoliomodel_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmemodel',
            name='image',
            field=models.ImageField(upload_to='about/images/'),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='images',
            field=models.ImageField(upload_to='portfolio/images/'),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='thumbnail',
            field=models.ImageField(upload_to='portfolio/images/'),
        ),
    ]
