# Generated by Django 4.0 on 2022-02-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapi', '0006_alter_aboutmemodel_image_alter_portfoliomodel_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagemodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='home/images/'),
        ),
        migrations.AlterField(
            model_name='aboutmemodel',
            name='experience',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aboutmemodel',
            name='paragraph',
            field=models.TextField(),
        ),
    ]
