# Generated by Django 4.0 on 2022-03-14 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dapi', '0007_homepagemodel_image_alter_aboutmemodel_experience_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioModelImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='portfolio/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='dapi.portfoliomodel')),
            ],
        ),
    ]
