# Generated by Django 4.0 on 2022-03-18 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dapi', '0008_portfoliomodelimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliomodel',
            name='images',
        ),
    ]
